services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: obor1234
      POSTGRES_DB: binance_trade_bot
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload --log-level=info
    env_file:
      - .env
    volumes:
      - ./app:/app
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A celery_app worker --loglevel=info --pool=prefork
    env_file:
      - .env
    volumes:
      - ./app:/app
    depends_on:
      - backend
      - redis
      - postgres
    environment:
      - PYTHONPATH=/app

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A celery_app beat --loglevel=debug
    env_file:
      - .env
    volumes:
      - ./app:/app
    depends_on:
      - backend
      - redis
      - postgres
    environment:
      - PYTHONPATH=/app


volumes:
  pg_data:
