services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7
    restart: always
    networks:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    command: >
      sh -c "python -m app.db.init_db && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - PYTHONPATH=/app/app
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env
    networks:
      - backend

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    working_dir: /app
    command: celery -A app.celery_app worker --loglevel=info
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - PYTHONPATH=/app/app
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - backend

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile.beat
    working_dir: /app
    command: celery -A app.celery_app beat --loglevel=info
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - PYTHONPATH=/app/app
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
