version: "3.9"

services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  redis:
    image: redis:7
    restart: always
    command: ["redis-server", "--requirepass", "${REDISPASSWORD}"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - backend

  backend:
    build:
      context: .
    command: >
      sh -c "ls -la && ls -la db && python db/init_db.py &&
            uvicorn app.main:app --host 0.0.0.0 --port 8000"
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - REDIS_URL=redis://:${REDISPASSWORD}@redis:6379/0
      - CELERY_BROKER_URL=redis://:${REDISPASSWORD}@redis:6379/0
      - CELERY_RESULT_BACKEND=redis://:${REDISPASSWORD}@redis:6379/1
      - PYTHONPATH=/app
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    networks:
      - backend

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    command: >
      sh -c "celery -A app.celery_app worker --loglevel=info"
    working_dir: /app
    volumes:
      - ./app:/app
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - REDIS_URL=redis://:${REDISPASSWORD}@redis:6379/0
      - CELERY_BROKER_URL=redis://:${REDISPASSWORD}@redis:6379/0
      - CELERY_RESULT_BACKEND=redis://:${REDISPASSWORD}@redis:6379/1
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    networks:
      - backend

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile.beat
    command: >
      sh -c "celery -A app.celery_app beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    working_dir: /app
    volumes:
      - ./app:/app
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - REDIS_URL=redis://:${REDISPASSWORD}@redis:6379/0
      - CELERY_BROKER_URL=redis://:${REDISPASSWORD}@redis:6379/0
      - CELERY_RESULT_BACKEND=redis://:${REDISPASSWORD}@redis:6379/1
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    networks:
      - backend

volumes:
  postgres_data:
  redis_data:

networks:
  backend:
    driver: bridge
